force-app/main/default/objects/Album__c/Album__c.object-meta.xml
<CustomObject>
    <label>Album</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Album Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Album__c/fields/Band__c.field-meta.xml
<CustomField>
    <fullName>Band__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Band</label>
    <referenceTo>Band__c</referenceTo>
    <relationshipLabel>Albums</relationshipLabel>
    <relationshipName>Albums</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Band__c/Band__c.object-meta.xml
<CustomObject>
    <label>Band</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Band Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Band__c/fields/Total_Songs_Number__c.field-meta.xml
<CustomField>
    <fullName>Total_Songs_Number__c</fullName>
    <label>Total Songs Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Song Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Album__c.field-meta.xml
<CustomField>
    <fullName>Album__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Album</label>
    <referenceTo>Album__c</referenceTo>
    <relationshipLabel>Songs</relationshipLabel>
    <relationshipName>Songs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Band__c.field-meta.xml
<CustomField>
    <fullName>Band__c</fullName>
    <label>Band</label>
    <referenceTo>Band__c</referenceTo>
    <relationshipLabel>Songs</relationshipLabel>
    <relationshipName>Songs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SongAmountBatch.cls
public with sharing class SongAmountBatch implements Database.Batchable<sObject>, Schedulable {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return Database.getQueryLocator('SELECT Id, Hit_Song__c, Album__r.Band__r.Id, Album__r.Band__r.Total_Songs_Number__c FROM Song__c'); 
    }
    public void execute(Database.BatchableContext bc, List<Song__c> records){
        // process each batch of records
        Map<String, Integer> bandIdToSongAmountMap = new Map<String, Integer>();
        for(Song__c song_i : records) { 
            if(song_i.Hit_Song__c == True) {
                if(bandIdToSongAmountMap.containsKey(song_i.Album__r.Band__r.Id)) {
                    Integer tempAmount = bandIdToSongAmountMap.get(song_i.Album__r.Band__r.Id);
                    tempAmount  += 1;
                    bandIdToSongAmountMap.put(song_i.Album__r.Band__r.Id, tempAmount);    
                } else {
                    bandIdToSongAmountMap.put(song_i.Album__r.Band__r.Id, 1);
                }
            }
        }
        if(!bandIdToSongAmountMap.isEmpty()) {
            List<Band__c> bandToUpdateList = new List<Band__c>();
            for(String key_i : bandIdToSongAmountMap.keySet()) {
                Integer tempAmount = bandIdToSongAmountMap.get(key_i);
                bandToUpdateList.add(new Band__c(id = key_i, Total_Songs_Number__c = tempAmount));
            }

            if(!bandToUpdateList.isEmpty()){
                update bandToUpdateList;
            }    
        }
    }

    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }

    // Database.schedule('My First Schedule', '0 9 * * *', new SongAmountBatchScheduler());
    public void execute(SchedulableContext sc){
        SongAmountBatch batch = new SongAmountBatch();
        database.executeBatch(batch);
    }  
}