force-app/main/default/objects/Band__c/Band__c.object-meta.xml
<CustomObject>
    <label>Band</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Band Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Band__c/fields/Band_Closing_Year__c.field-meta.xml
<CustomField>
    <fullName>Band_Closing_Year__c</fullName>
    <label>Band Closing Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Band__c/fields/Year_Of_Foundation__c.field-meta.xml
<CustomField>
    <fullName>Year_Of_Foundation__c</fullName>
    <label>Year Of Foundation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CreateNewBandController.cls
public with sharing class CreateNewBandController {
    @AuraEnabled
    public static string createNewBand(String name, String country, String yearOfFoundation, String bandClosingYear) {
        try {
            insert new Band__c(Name__c = name, Country__c = country, Year_Of_Foundation__c = Date.valueOf(yearOfFoundation), Band_Closing_Year__c = Date.valueOf(bandClosingYear));
            return 'Success';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}