force-app/main/default/objects/Band__c/Band__c.object-meta.xml
<CustomObject>
    <label>Band</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Band Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Band__c/fields/Band_Closing_Year__c.field-meta.xml
<CustomField>
    <fullName>Band_Closing_Year__c</fullName>
    <label>Band Closing Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Band__c/fields/Closing_Date_On_Opening_Day__c.field-meta.xml
<CustomField>
    <fullName>Closing_Date_On_Opening_Day__c</fullName>
    <label>Closing Date On Opening Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Band__c/fields/IsGroupExistOneDay__c.field-meta.xml
<CustomField>
    <fullName>IsGroupExistOneDay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsGroupExistOneDay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Band__c/fields/Year_Of_Foundation__c.field-meta.xml
<CustomField>
    <fullName>Year_Of_Foundation__c</fullName>
    <label>Year Of Foundation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BandTriggerHandler.cls
public with sharing class BandTriggerHandler {

    public void beforeInsert(List<Band__c> bandList) {
        for (Band__c band_i : bandList) {
            if(band_i.Band_Closing_Year__c == band_i.Year_Of_Foundation__c) {
                
                if(band_i.IsGroupExistOneDay__c) { 
                    band_i.Closing_Date_On_Opening_Day__c = band_i.Band_Closing_Year__c;
                    band_i.Band_Closing_Year__c = Null;
                }
            }
        }
    } 
}